on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
          - windows
    name: Acceptance Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run tests
        run: |
          cargo test --all --features mock-network
      - name: Lint with clippy
        run: cargo clippy
      - name: Lint tests with clippy
        run: |
          cargo clippy --tests --features mock-network

  smoke-tests:
    name: Smoke Tests
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run tests
        run: |
          cargo test --test smoke --features smoke-tests -- --test-threads 1

  shell-tests:
    name: Shell Script Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        run: sudo npm install -g bats
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests
        run: bats dev/unix/tests/

  check-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run check
        run: |
          cargo fmt --all --quiet -- --check
